version: "1.0"
name: Hello World
config:
  http:
    baseURL: http://localhost:3000/api
tests:
  default:
    name: Default
    steps:
      - http:
          url: /hello
          method: GET
          params:
            name: aliquip dolor
          check:
            status: 200
components:
  schemas: {}
